### ISSUE TITLE
recommended commandline

### ISSUE THREAD

**Issue by mgaulton** [dpisano/docker-bro#3]
Just looking for suggestions on what the best options to run this with.

**Comment by dpisano** [comment]
I'm using `-d --net=host -v /opt/bro/logs:/opt/bro/logs -v /opt/bro/spool:/opt/bro/spool`. As I'm still working on it right now I don't have much documentation. Also I don't have any image of it up on Docker Hub. If you do build to form the Dockerfile it will take about 20 min to do so.

**Comment by mgaulton** [comment]
thank you, that's what I was looking for.

I was going to try building it, just to experiment. I'm in the elusive hunt for Bro+Elk running in docker lol
